[project]
name = "Runna-backend"
version = "0.1.0"
description = "Run your code with serverless"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.122.0",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]
